version: "3.8"
services:
  wds-blogs-nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-blogs-nginx.rule=Host(`blogs.localhost`)"
      - "traefik.http.services.wds-blogs-nginx.loadbalancer.server.port=80"
    networks:
      - app-blogs-network
      - frontend

  wds-blogs:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: on-failure
    networks:
      - app-blogs-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0

    # env_file:
    #   - ./.env.local
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./public:/app/public

networks:
  app-blogs-network:
    name: app-blogs-network

  frontend:
    name: frontend
