version: "3.8"
# commands url http://host.docker.internal:6777
services:
  wds-blogs-nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8088:80"
    networks:
      - wds-blogs-nginx-network

  wds-blogs:
    image: "ghassanaldarwish/wds-blogs"
    restart: on-failure
    networks:
      - wds-blogs-nginx-network

    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production

    env_file:
      - ../environment/wds-blogs/.env.local

networks:
  wds-blogs-nginx-network:
    name: wds-blogs-nginx-network
