version: "3.8"
# commands url http://host.docker.internal:6777
services:
  wds-blogs-nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    networks:
      - wds-blogs-nginx-network
      - app-workspace-network
    ports:
      - "8088:80"

  wds-blogs:
    image: "ghassanaldarwish/wds-blogs"
    restart: on-failure
    networks:
      - wds-blogs-nginx-network
      - app-workspace-network
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production

    env_file:
      - ../environment/wds-blogs/.env.local

  # wds-blogs-api-auth:
  #   image: "ghassanaldarwish/api-auth"

  #   env_file:
  #     - ../environment/wds-blogs/.env.local
  #   environment:
  #     - PORT=3013
  #     - NODE_ENV=production
  #     - DB_NAME=auth
  #     - ROLE=admin
  #     - CACHE_HOST=api-cache
  #     - DB_URI=mongodb://api-db
  #     - SERVICE_NAME=auth
  #     - KAFKA_BROKER_LISTENER=kafka:9092
  #   restart: on-failure
  #   networks:
  #     - wds-blogs-nginx-network
  #     - app-workspace-network

networks:
  wds-blogs-nginx-network:
    name: wds-blogs-nginx-network

  app-workspace-network:
    name: app-workspace-network
